### ISSUE TITLE
java8 platform

### ISSUE THREAD

**Issue by vmalaga** [tsuru/basebuilder#100]
Hi  @fsouza 

we have some apps that use the old java 8 platform, but now there is only one java platform based on openjdk.

Our developers ask me if there is any possibility of having it again ?

**Comment by andrewsmedina** [comment]
@vmalaga if you want to use the oracle jvm you can create your own platform based on the old java platform.

**Comment by fsouza** [comment]
@vmalaga we've removed the public Oracle Java platform because it accepted automatically the Oracle license, we weren't confident that this is legal x)

Maybe you can have non-public platform that does that, and store the built image in your internal registry.

**Comment by vmalaga** [comment]
Yes I understand. I am going to build and internal platform for that.

thanks
