### ISSUE TITLE
nodejs: remove 'npm install' from deploy script

### ISSUE THREAD

**Issue by guestisp** [tsuru/basebuilder#12]
Many apps needs to be installed with a custom environment, for example 'development' or 'production'

Actually, each deploy will run an 'npm install' with defaults that in most cases could not be ok.

Install should be done client-side, like on heroku, and then push to tsuru the whole application (with dependances installed)

For example, with the actual workflow, is not possible to use Ghost blogging platform with the suggested production environment. "npm install" will defaults to 'development' and it will add tons of unneeded dependances. Actually, in tsuru, there isn't any way to use 'npm install --production' due to the hardcoded 'npm install' in deploy script.

Removing that, allows customers to run 'npm install --production' client-side and push that through git.

Info: https://devcenter.heroku.com/articles/getting-started-with-nodejs

**Comment by fsouza** [comment]
This has been around for a while and we never came to conclusion, maybe we can raise this question again in the new platforms repository: https://github.com/tsuru/platforms/issues.
