### ISSUE TITLE
base image: remove g++ and build tools

### ISSUE THREAD

**Issue by guestisp** [tsuru/basebuilder#17]
g++ and any build tools requirements should be removed from the base image.
Installing that will result in 213 MB of packages (build-essential and so on) making the final image size more or less 500MB:

apt-get output:

   After this operation, 213 MB of additional disk space will be used.

why not using a compiled version of tsuru-circus ? base image is Ubuntu Quantal so it should be possible to precompile packages

**Comment by kinosang** [comment]
agree with it. in fact, more than half of tsuru images do not need g++ and build tools.

**Comment by fsouza** [comment]
As we don't have circus anymore, this is now done.
