### ISSUE TITLE
php platform with interpretor on tsurud version 0.12.2

### ISSUE THREAD

**Issue by vmalaga** [tsuru/basebuilder#93]
Hello.

we are migrating tsuru to the 0.12.2 version and have find that this platform is broken when you use interpretor on tsuru.yml

The problem is that using interpretor, the platform fill the Procfile with 2 entries

```
frontend: /usr/sbin/apache2 -d /etc/apache2 -k start -DNO_DETACH
interpretor: /usr/sbin/php5-fpm --fpm-config /etc/php5/fpm/php-fpm.conf
```
the first is easy changing it to web on custom Procfile, but the second start one docker container completly separated by from apache so it does not work

How can I start the php interpretor inside the same container of the apache container ?

**Comment by fsouza** [comment]
It's now fixed, thank you for reporting!
