### ISSUE TITLE
node: read node version from package.json

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/basebuilder#95]
It is possible to specify the node version in package.json with the `engine` attribute:

```
{
  "name": "myapp",
  "version": "0.1.1",
  ...
  "dependencies": {
  ...
  "engines": {
    "node": "0.12.2"
  },
}
```

tsuru can use this attribute to discover the node version.

**Comment by fsouza** [comment]
Migrated to tsuru/platforms#2.
