### ISSUE TITLE
Ruby platform broken for 1.9.3 - always falls back to 2.2

### ISSUE THREAD

**Issue by mtekel** [tsuru/basebuilder#96]
Hi,

looks like ruby version parsing is broken. When I try to deploy [this](https://github.com/alphagov/example-ruby-sinatra) app, where .ruby-version contains `1.9.3-p125` and Gemfile 
```
source 'http://rubygems.org'
ruby '1.9.3'
gem 'sinatra'
gem 'rack'
```
The parsed ruby version is 1.9, which then falls back to 2.2:
```
Uploading files..... ok
WARNING: Invalid ruby version, please use 1.9.1, 1.9.3, 2.0, 2.1 or 2.2. Using ruby 2.2 as fallback.
-- Using ruby version: 1.9 --
```
The bundler then fails with `Your Ruby version is 2.2.3, but your Gemfile specified 1.9.3`

I suspect the problem is somewhere around [these lines](https://github.com/tsuru/basebuilder/blob/master/ruby/deploy#L23), as it seem to return only first two numbers from the version string. Alternatively, [this condition](https://github.com/tsuru/basebuilder/blob/master/ruby/deploy#L29) could be adjusted to check just for 1.9. I have not investigated further. I have tried changing .ruby-version to `1.9.3`, but that didn't fix the issue.

**Comment by morpheu** [comment]
Thanks! First option in case was the problem - regex for version switch always match the two first digits instead three. Already fixed.

**Comment by mtekel** [comment]
Thanks!
